NLayer.WebUI/Controllers/WriterPanelContentController.cs
using NLayer.BusinessLayer.Concrete;
using NLayer.DataAccessLayer.Concrete;
using NLayer.DataAccessLayer.EntityFramework;
using NLayer.EntityLayer.Concrete;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace NLayer.WebUI.Controllers
{
    public class WriterPanelContentController : Controller
    {
        ContentManager cm = new ContentManager(new EfContentDal());

        Context c = new Context();

        // GET: WriterPanelContent
        public ActionResult MyContent(string p)
        {
            

            p = (string)Session["WriterMail"];

            //sisteme girin yazarın email adresine göre Sessina veri aktarabilmek için tanımlandı
            var writeridinfo = c.Writers.Where(x => x.WriterMail == p).Select(y => y.WriterID).FirstOrDefault();

            var contentvalues = cm.GetListByWriter(writeridinfo);

            return View(contentvalues);
        }

        //başlığın içindeki içeriklere yazı yazma sayfası
        public ActionResult AddContent(int id)
        {
            ViewBag.d = id;

            return View();
        }

        [HttpPost]
        public ActionResult AddContent(Content p)
        {
            string mail= (string)Session["WriterMail"];

            //sisteme girin yazarın email adresine göre Sessina veri aktarabilmek için tanımlandı
            var writeridinfo = c.Writers.Where(x => x.WriterMail == mail).Select(y => y.WriterID).FirstOrDefault();

            p.ContentDate =DateTime.Parse(DateTime.Now.ToShortDateString());

            p.WriterID = writeridinfo;
            p.ContentStatus = true;

            cm.ContentAdd(p);

            return RedirectToAction("MyContent");
        }

        public ActionResult ToDoList()
        {
            return View();
        }
    }
}

NLayer.WebUI/Views/WriterPanelContent/AddContent.cshtml
@model NLayer.EntityLayer.Concrete.Content
@{
    ViewBag.Title = "İçerik Girişi";
    Layout = "~/Views/Shared/_WriterLayout.cshtml";
}

<h2>@ViewBag.Title</h2>

<br />

@using (Html.BeginForm("AddContent", "WriterPanelContent", FormMethod.Post))
{
    <div class="form-group">
        <input type="hidden" name="HeadingID" value="@ViewBag.d" />

        @* başlık adı 4 ve 30 değerleri textarea değerinin büyüklüğünü belirler *@
        @Html.Label("İçeriğinizi yazın")
        @Html.TextAreaFor(x => x.ContentValue,4,30, new { @class = "form-control" })
        @Html.ValidationMessageFor(x => x.ContentValue)

        <br />

        @* buton bölümü *@
        <button class="btn btn-info">Kaydet</button>

    </div>
}

NLayer.WebUI/Views/WriterPanelContent/MyContent.cshtml
@using NLayer.EntityLayer.Concrete
@model List<Content>
@{
    ViewBag.Title = "MyContent";
    Layout = "~/Views/Shared/_WriterLayout.cshtml";
}

<h2></h2>

@foreach (var item in Model)
{
    <p>@item.Heading.HeadingName</p>
    <p>@item.ContentDate.ToShortDateString()</p>
    <p>@item.ContentValue</p>
    <hr />
}

NLayer.WebUI/Views/WriterPanelContent/ToDoList.cshtml
@{
    ViewBag.Title = "ToDoList";
    Layout = "~/Views/Shared/_WriterLayout.cshtml";
}

<h2>ToDoList</h2>

<p>#1 Profilim</p>
<p><del>#2 Tüm başlıklarda sayfalama yapılacak</del></p>
<p><del>#3 Mesajlarda Session</del></p>
<p><del>#4 Oturum yönetiminin mimariye taşınmamsı</del></p>
<p>#5 Token kullanılması</p>