NLayer.WebUI/Controllers/HeadingController.cs
using NLayer.BusinessLayer.Concrete;
using NLayer.DataAccessLayer.EntityFramework;
using NLayer.EntityLayer.Concrete;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace NLayer.WebUI.Controllers
{
    public class HeadingController : Controller
    {
        HeadingManager hm = new HeadingManager(new EfHeadingDal());
        CategoryManager cm = new CategoryManager(new EfCategoryDal());

        WriterManager wm = new WriterManager(new EWriterDal());

        // GET: Heading
        public ActionResult Index()
        {
            var headingvalues = hm.GetList();

            return View(headingvalues);
        }

        public ActionResult HeadingReport()
        {
            var headingvalues = hm.GetList();

            return View(headingvalues);
        }

        #region Başlık Ekleme bölümü

        [HttpGet]
        public ActionResult AddHeading()
        {
            List<SelectListItem> valuecategory = (from x in cm.GetList()
                                                  select new SelectListItem
                                                  {
                                                      Text=x.CategoryName,
                                                      Value=x.CategoryID.ToString()
                                                  }).ToList();

            ViewBag.vlc = valuecategory;


            List<SelectListItem> valuewriter = (from x in wm.GetList()
                                                  select new SelectListItem
                                                  {
                                                      Text = x.WriterName+" "+ x.WriterSurname,
                                                      Value = x.WriterID.ToString()
                                                  }).ToList();

            ViewBag.vlw = valuewriter;

            return View();
        }

        [HttpPost]
        public ActionResult AddHeading(Heading p)
        {
            p.HeadingDate =DateTime.Parse(DateTime.Now.ToShortDateString());
            hm.HeadingAdd(p);
            return RedirectToAction("Index");
        }

        #endregion


        #region Başlık Düzenleme Bölümü

        [HttpGet]
        public ActionResult EditHeading(int id)
        {
            var headingvalue = hm.GetByID(id);

            List<SelectListItem> valuecategory = (from x in cm.GetList()
                                                  select new SelectListItem
                                                  {
                                                      Text = x.CategoryName,
                                                      Value = x.CategoryID.ToString()
                                                  }).ToList();

            ViewBag.vlc = valuecategory;


            List<SelectListItem> valuewriter = (from x in wm.GetList()
                                                select new SelectListItem
                                                {
                                                    Text = x.WriterName + " " + x.WriterSurname,
                                                    Value = x.WriterID.ToString()
                                                }).ToList();

            ViewBag.vlw = valuewriter;

            return View(headingvalue);
        }

        [HttpPost]
        public ActionResult EditHeading(Heading p)
        {
            hm.HeadingUpdate(p);

            return RedirectToAction("Index");
        }

        #endregion

        #region Başlık Silme Bölümü

        
        public ActionResult DeleteHeading(int id)
        {
            var headingvalue = hm.GetByID(id);

            headingvalue.HeadingStatus = false;

            hm.HeadingDelete(headingvalue);

            return RedirectToAction("Index");
        }

        #endregion

        //yazarlara ait içerikleri getirir
        public ActionResult ContentByHeading()
        {
            return View();
        }
    }
}

NLayer.WebUI/Views/Heading/AddHeading.cshtml
@model NLayer.EntityLayer.Concrete.Heading
@{
    ViewBag.Title = "AddWriter";
}

<h2>Yeni Başlık Ekleme</h2>

<br />

@using (Html.BeginForm("AddHeading", "Heading", FormMethod.Post))
{
<div class="form-group">
    @* başlık adı *@
    @Html.Label("Başlık Adı")
    @Html.TextBoxFor(x => x.HeadingName, new { @class = "form-control" })
    @Html.ValidationMessageFor(x => x.HeadingName)

    <br />

    @* kategori dropdown *@
    @Html.Label("Kategori")
    @Html.DropDownListFor(x => x.CategoryID, (List<SelectListItem>)ViewBag.vlc, new { @class = "form-control" })
    @Html.ValidationMessageFor(x => x.CategoryID)

    <br />

    @* yazar dropdown *@
    @Html.Label("Yazar")
    @Html.DropDownListFor(x => x.WriterID, (List<SelectListItem>)ViewBag.vlw, new { @class = "form-control" })
    @Html.ValidationMessageFor(x => x.WriterID)

    <br />

    @* buton bölümü *@
    <button class="btn btn-info">Başlık Ekle</button>

</div>
}

NLayer.WebUI/Views/Heading/EditHeading.cshtml
@model NLayer.EntityLayer.Concrete.Heading
@{
    ViewBag.Title = "EditHeading";
}

<h2>Yeni Başlık Güncelleme</h2>

<br />

@using (Html.BeginForm("EditHeading", "Heading", FormMethod.Post))
{
<div class="form-group">
    @Html.HiddenFor(x => x.HeadingID)

    @* başlık adı *@
    @Html.Label("Başlık Adı")
    @Html.TextBoxFor(x => x.HeadingName, new { @class = "form-control" })
    @Html.ValidationMessageFor(x => x.HeadingName)

    <br />

    @* tarih bölümü *@
    @Html.Label("Başlık Tarihi")
    @Html.TextBoxFor(x => x.HeadingDate, new { @class = "form-control" })

    <br />

    @* kategori dropdown *@
    @Html.Label("Kategori")
    @Html.DropDownListFor(x => x.CategoryID, (List<SelectListItem>)ViewBag.vlc, new { @class = "form-control" })
    @Html.ValidationMessageFor(x => x.CategoryID)

    <br />

    @* yazar dropdown *@
    @Html.Label("Yazar")
    @Html.DropDownListFor(x => x.WriterID, (List<SelectListItem>)ViewBag.vlw, new { @class = "form-control" })
    @Html.ValidationMessageFor(x => x.WriterID)

    <br />

    @* buton bölümü *@
    <button class="btn btn-info">Başlık Güncelle</button>

</div>
}

NLayer.WebUI/Views/Heading/HeadingReport.cshtml
@using NLayer.EntityLayer.Concrete
@model List<Heading>

@{
    ViewBag.Title = "HeadingReport";
    //Layout = "~/Views/Shared/_SiteLayout.cshtml";
    Layout = null;
}

<br />
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Raporlama Sayfası</title>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.1.1/css/bootstrap.css">
    <link rel="stylesheet" href="https://cdn.datatables.net/1.10.19/css/dataTables.bootstrap4.min.css">
    <link rel="stylesheet" href="https://cdn.datatables.net/buttons/1.5.2/css/buttons.bootstrap4.min.css">
    <link rel="stylesheet" href="https://cdn.datatables.net/responsive/2.2.3/css/responsive.bootstrap4.min.css">
</head>
<body>
    <table id="example" class="table table-striped table-bordered dt-responsive nowrap" style="width:100%">
        <thead>
            <tr>
                <th>Başlık Id</th>
                <th>Başlık ad</th>
                <th>Tarih</th>
                <th>Yazar</th>
                <th>Kategori</th>
                <th>Durum</th>
            </tr>
        </thead>
        <tbody>
            @foreach (var x in Model)
            {
                <tr>
                    <td>@x.HeadingID</td>
                    <td>@x.HeadingName</td>
                    <td>@x.HeadingDate</td>
                    <td>@x.Writer.WriterName @x.Writer.WriterSurname</td>
                    <td>@x.Category.CategoryName</td>
                    <td>@x.HeadingStatus</td>
                </tr>
            }

        </tbody>
    </table>
    <script src="https://code.jquery.com/jquery-3.3.1.js"></script>
    <script src="https://cdn.datatables.net/1.10.19/js/jquery.dataTables.min.js"></script>
    <script src="https://cdn.datatables.net/1.10.19/js/dataTables.bootstrap4.min.js"></script>
    <script src="https://cdn.datatables.net/buttons/1.5.2/js/dataTables.buttons.min.js"></script>
    <script src="https://cdn.datatables.net/buttons/1.5.2/js/buttons.bootstrap4.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jszip/3.1.3/jszip.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/pdfmake/0.1.36/pdfmake.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/pdfmake/0.1.36/vfs_fonts.js"></script>
    <script src="https://cdn.datatables.net/buttons/1.5.2/js/buttons.html5.min.js"></script>
    <script src="https://cdn.datatables.net/buttons/1.5.2/js/buttons.print.min.js"></script>
    <script src="https://cdn.datatables.net/buttons/1.5.2/js/buttons.colVis.min.js"></script>
    <script src="https://cdn.datatables.net/responsive/2.2.3/js/dataTables.responsive.min.js"></script>
    <script src="https://cdn.datatables.net/responsive/2.2.3/js/responsive.bootstrap4.min.js"></script>
    <script>
	$(document).ready(function() {
	    var table = $('#example').DataTable( {
	        lengthChange: false,
	        buttons: [ 'copy', 'excel', 'csv', 'pdf', 'colvis' ]
	    } );

	    table.buttons().container()
	        .appendTo( '#example_wrapper .col-md-6:eq(0)' );
	} );
    </script>
</body>
</html>

NLayer.WebUI/Views/Heading/Index.cshtml
@using NLayer.EntityLayer.Concrete
@model List<Heading>
@{
    ViewBag.Title = "Index";
}

@{ 
    string color = "";
}

<h2>Index</h2>

<br />

<a href="/Heading/AddHeading">Ekle</a>

<table class="table table-hover table-responsive ">
    <tr>
        <th>#</th>
        <th>Başlık Adı</th>
        <th>Kategori</th>
        <th>Durum</th>
        <th></th>
    </tr>
    @foreach (var item in Model)
    {
<tr>
    <td>@item.HeadingID</td>
    <td>@item.HeadingName</td>
    @if (item.Category.CategoryName == "Tiyatro")
    {
        color = "text-danger";
    }
    <td class="@color">@item.Category.CategoryName</td>
    <td>@item.HeadingStatus</td>
    <td>
        <a href="/Content/ContentByHeading/@item.HeadingID">Yazara ait Yazılar</a>

        <a href="/Heading/EditHeading/@item.HeadingID">Düzenle</a>

        <a href="/Heading/DeleteHeading/@item.HeadingID">Sil</a>
    </td>
</tr>
    }

</table>